"""
Court-output helpers beyond the main report:

* affidavit_text()          - DRAFT methodology paragraphs for a search-
                              warrant affidavit ("how this tracing was
                              performed"), for counsel to adapt.
* traceroute_text()         - the warrant-ready hop-by-hop path for one
                              exit (server-side twin of the UI export).
* build_evidence_package()  - one ZIP with every artifact of a trace
                              (report PDF, custody CSV, raw JSON,
                              affidavit, traceroutes, freeze letters) and
                              a MANIFEST listing the SHA-256 of each file,
                              ready to hand over in discovery.
"""

import csv
import hashlib
import io
import json
import zipfile
from datetime import datetime, timezone

from app import config
from app.labels import store as label_store
from app.report import freeze_letter, pdf_report

AFFIDAVIT_DISCLAIMER = (
    "DRAFT - FOR REVIEW AND ADAPTATION BY THE AFFIANT AND PROSECUTOR. "
    "These paragraphs describe the tracing methodology factually; the "
    "affiant must verify each statement, adapt the language to the "
    "jurisdiction's affidavit practice, and swear only to what they "
    "personally reviewed.")


def _now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _fmt_ts(unix_ts) -> str:
    if not unix_ts:
        return "-"
    return datetime.fromtimestamp(unix_ts, tz=timezone.utc
                                  ).strftime("%Y-%m-%d %H:%M:%S UTC")


def _fmt_amount(value) -> str:
    return f"{value:,.6f}".rstrip("0").rstrip(".")


# ---------------------------------------------------------------------------
# Affidavit methodology paragraphs
# ---------------------------------------------------------------------------

def affidavit_text(case: dict, trace_row: dict, result: dict,
                   custody_count: int, agency: dict) -> str:
    """DRAFT affidavit paragraphs describing the tracing methodology."""
    chain_name = result["chain"].capitalize()
    backward = result.get("direction") == config.DIRECTION_BACKWARD
    officer = agency.get("officer_name") or "[AFFIANT NAME]"
    officer_title = agency.get("officer_title") or "[TITLE / RANK]"
    agency_name = agency.get("agency_name") or "[AGENCY NAME]"

    if result["chain"] == config.CHAIN_BITCOIN:
        sources = ("public Esplora-compatible block-explorer APIs "
                   "(mempool.space and blockstream.info)")
    elif result["chain"] == config.CHAIN_ETHEREUM:
        sources = "the public Etherscan API"
    else:
        sources = "the public TronGrid API (Tron's official API service)"

    exits = result.get("exits") or []
    exit_sentence = ""
    if exits:
        listed = "; ".join(
            f"{e['entity']} (address {e['address']}, "
            f"{', '.join(f'{_fmt_amount(v)} {a}' for a, v in e['totals'].items())})"
            for e in exits[:5])
        if backward:
            exit_sentence = (
                f"The analysis identified the following custodial "
                f"service(s) from which the traced funds originated: "
                f"{listed}.")
        else:
            exit_sentence = (
                f"The analysis identified the following custodial "
                f"service(s) that received traced funds: {listed}.")

    paragraphs = [
        AFFIDAVIT_DISCLAIMER,
        "",
        f"Generated by {config.APP_NAME} v{config.APP_VERSION} on "
        f"{_now_utc()} for case '{case['name']}'"
        + (f" ({case['case_number']})" if case.get("case_number") else "")
        + f", trace #{trace_row['id']}.",
        "",
        f"1. I, {officer}, {officer_title}, {agency_name}, conducted a "
        f"blockchain analysis of the {chain_name} address "
        f"{result['victim_address']}"
        + (" to determine the source of the funds it holds or held."
           if backward else
           " to follow the movement of funds taken from the victim.")
        + " The analysis was performed with a software tool that retrieves "
        "public blockchain records and presents them for review; every "
        "factual statement below is verifiable against the public "
        "blockchain by any analyst.",
        "",
        f"2. Data sources. All blockchain data was obtained from {sources}. "
        f"Blockchain transaction records are public, append-only records "
        f"maintained by the {chain_name} network's distributed consensus; "
        f"transaction identifiers, addresses, amounts and timestamps cited "
        f"in this affidavit can be independently verified on any public "
        f"block explorer.",
        "",
        f"3. Method. {result.get('accounting_method', '')}",
        "",
        f"4. Scope. The trace examined {result['stats']['addresses']} "
        f"address(es) and followed {result['stats']['edges']} on-chain "
        f"movement(s)"
        + (f" using the '{result.get('search_pattern')}' branch-selection "
           f"pattern" if result.get("search_pattern") else "")
        + ". Where branches were left unexamined (value below the dust "
        "threshold, branch-selection rules, or trace size limits), the "
        "tool recorded and reported them; selective examination was never "
        "presented as complete examination.",
        "",
        "5. Attribution and confidence. Where an address is attributed to "
        "a real-world service, the attribution's source and confidence "
        "level are stated in the accompanying fund-tracing report: "
        "HIGH for official sources (the U.S. Treasury OFAC SDN list) or "
        "multiple corroborating sources; MEDIUM for a single reputable "
        "public/community source; LOW for heuristic inferences produced "
        "by the tool's own analysis. Attribution of an address to a "
        "service does not identify the account holder; account-holder "
        "identity must be obtained from the service's records via legal "
        "process. The tool does not fabricate continuity: funds entering "
        "mixing services, privacy protocols or unresolvable branches are "
        "reported as such.",
        "",
        f"6. Records integrity. Each of the {custody_count} data "
        f"acquisition(s) performed for this trace was logged with its "
        f"exact request URL, UTC timestamp, HTTP status, and the SHA-256 "
        f"hash of the raw response as received. The complete "
        f"chain-of-custody log accompanies the fund-tracing report and "
        f"permits any analyst to re-issue the same requests and compare "
        f"hashes.",
    ]
    clusters = [c for c in (result.get("clusters") or [])
                if len(c.get("traced_addresses", [])) >= 2]
    if clusters:
        paragraphs += [
            "",
            f"6a. Address clustering. For {len(clusters)} group(s) of "
            f"addresses the tool applied the common-input-ownership "
            f"heuristic, under which all inputs of a single Bitcoin "
            f"transaction are presumed to have been controlled by one "
            f"party at the time of spending. Transactions exhibiting "
            f"CoinJoin characteristics were excluded. Each cluster is "
            f"identified in the report with the transaction(s) evidencing "
            f"it and a stated confidence level; clustering is an inference "
            f"drawn from public data, not a determination of identity.",
        ]
    if exit_sentence:
        paragraphs += ["", f"7. Result. {exit_sentence} The hop-by-hop "
                       "path from the starting address to each service, "
                       "with transaction identifiers, amounts and "
                       "timestamps, is attached."]
    return "\n".join(paragraphs)


# ---------------------------------------------------------------------------
# Traceroute (server-side twin of the UI export)
# ---------------------------------------------------------------------------

def traceroute_text(result: dict, exit_entry: dict, trace_id) -> str:
    """Plain-text hop-by-hop fund-flow path for one exit."""
    backward = result.get("direction") == config.DIRECTION_BACKWARD
    chain_name = result["chain"].capitalize()
    lines = [
        "CRYPTOCURRENCY FUND-FLOW PATH (TRACEROUTE)",
        f"Generated by {config.APP_NAME} v{result.get('app_version', config.APP_VERSION)} "
        f"on {_now_utc()} - trace #{trace_id}",
        f"Blockchain: {chain_name}",
    ]
    if backward:
        lines.append(f"Target wallet (funds traced backward from): "
                     f"{result.get('victim_address')}")
        lines.append(f"Identified source: {exit_entry['entity']} - "
                     f"address {exit_entry['address']}")
    else:
        lines.append(f"Victim wallet: {result.get('victim_address')}")
        if result.get("focus_txid"):
            lines.append(f"Focus transaction: {result['focus_txid']} "
                         f"(only this payment was followed)")
        lines.append(f"Destination: {exit_entry['entity']} - deposit "
                     f"address {exit_entry['address']}")
    lines.append(f"Attribution: {exit_entry['confidence'].upper()} "
                 f"confidence (source: {exit_entry['source']})")
    compliance = exit_entry.get("compliance")
    if compliance:
        status = ("COMPLIANT" if compliance["status"] == "compliant"
                  else "NON-COMPLIANT")
        lines.append(
            f"Compliance designation: {status} - designated by the "
            f"investigating agency with reference to FATF guidance (not "
            f"an official FATF publication)"
            + (f"; {compliance['note']}" if compliance.get("note") else ""))
    path = exit_entry.get("path") or []
    lines.append(f"Path length: {len(path)} hop(s)")
    lines.append("")
    for hop in path:
        usd = hop.get("value_usd")
        usd_text = (f" (approx. ${usd:,.2f} USD at the transaction "
                    f"date's daily price)" if usd is not None else "")
        lines += [
            f"Hop {hop['hop']} of {len(path)}",
            f"  From:         {hop['from_address']}",
            f"  To:           {hop['to_address']}",
            f"  Amount:       {_fmt_amount(hop['value'])} "
            f"{hop['asset']}{usd_text}",
            f"  Transaction:  {hop['txid']}",
            f"  Date/time:    {_fmt_ts(hop['timestamp'])}",
            "",
        ]
    lines.append(
        "NOTES: Transaction IDs, addresses, amounts and timestamps above "
        "are public blockchain records, independently verifiable on any "
        "block explorer. The exchange attribution and USD figures are "
        "inferences/estimates whose sources and confidence are stated "
        "above and detailed in the accompanying fund-tracing report.")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Evidence / disclosure package
# ---------------------------------------------------------------------------

def _custody_csv(custody_entries: list) -> str:
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=[
        "id", "trace_id", "source", "url", "http_status", "sha256",
        "from_cache", "fetched_utc"])
    writer.writeheader()
    writer.writerows(custody_entries)
    return buffer.getvalue()


def build_evidence_package(zip_path: str, case: dict, trace_row: dict,
                           result: dict, custody_entries: list,
                           agency: dict, annotations: dict,
                           work_dir) -> list:
    """Assemble the disclosure ZIP. Returns the manifest rows
    [(filename, sha256, description)]. `work_dir` is a Path for the
    intermediate PDF files."""
    trace_id = trace_row["id"]
    files = []      # (arcname, bytes, description)

    # 1. Court report PDF.
    report_path = work_dir / f"trace_{trace_id}_report.pdf"
    pdf_report.build_report(str(report_path), case, trace_row, result,
                            custody_entries, annotations=annotations)
    files.append((f"fund_tracing_report_trace{trace_id}.pdf",
                  report_path.read_bytes(),
                  "Court-ready fund-tracing report"))

    # 2. Chain-of-custody CSV (complete log).
    files.append((f"chain_of_custody_trace{trace_id}.csv",
                  _custody_csv(custody_entries).encode("utf-8"),
                  "Complete chain-of-custody log (every data pull: URL, "
                  "UTC time, SHA-256 of raw response)"))

    # 3. Raw trace data.
    files.append((f"trace_{trace_id}_raw.json",
                  json.dumps(result, indent=1).encode("utf-8"),
                  "Complete machine-readable trace result"))

    # 4. Affidavit methodology draft.
    files.append((f"DRAFT_affidavit_methodology_trace{trace_id}.txt",
                  affidavit_text(case, trace_row, result,
                                 len(custody_entries),
                                 agency).encode("utf-8"),
                  "DRAFT affidavit methodology paragraphs (counsel to "
                  "adapt)"))

    # 5. Traceroute + DRAFT freeze letter per exit.
    for index, exit_entry in enumerate(result.get("exits") or [],
                                       start=1):
        safe_entity = "".join(
            ch if ch.isalnum() else "_"
            for ch in exit_entry["entity"])[:40] or "exit"
        if exit_entry.get("path"):
            files.append((
                f"traceroute_{index}_{safe_entity}.txt",
                traceroute_text(result, exit_entry,
                                trace_id).encode("utf-8"),
                f"Hop-by-hop fund-flow path to {exit_entry['entity']}"))
        address = exit_entry["address"]
        node = next((n for n in result["nodes"]
                     if n["address"] == address), None)
        funding_edges = [e for e in result["edges"]
                         if e["to_address"] == address
                         or e["from_address"] == address]
        if node and funding_edges:
            letter_path = work_dir / f"freeze_{trace_id}_{index}.pdf"
            entity = exit_entry["entity"]
            freeze_letter.build_freeze_request(
                str(letter_path), case, result, address, node,
                funding_edges, entity,
                label_store.custodian_lookup(entity),
                label_store.compliance_lookup(entity), agency)
            files.append((
                f"DRAFT_freeze_request_{index}_{safe_entity}.pdf",
                letter_path.read_bytes(),
                f"DRAFT preservation/freeze request to "
                f"{exit_entry['entity']}"))

    # Manifest with hashes, then the ZIP itself.
    manifest_rows = [(name, hashlib.sha256(content).hexdigest(),
                      description) for name, content, description in files]
    manifest_lines = [
        f"EVIDENCE PACKAGE MANIFEST - {config.APP_NAME} "
        f"v{config.APP_VERSION}",
        f"Case: {case['name']}"
        + (f" ({case['case_number']})" if case.get("case_number") else ""),
        f"Trace: #{trace_id} ({result['chain']}, "
        f"{result.get('direction', 'forward')})",
        f"Generated: {_now_utc()}",
        "",
        "Files (SHA-256 of each file as packaged):",
        "",
    ]
    for name, digest, description in manifest_rows:
        manifest_lines += [name, f"  SHA-256: {digest}",
                           f"  {description}", ""]
    manifest_lines.append(
        "Verify any file by recomputing its SHA-256 and comparing with "
        "this manifest. DRAFT documents require review by the "
        "prosecuting authority before service.")

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as bundle:
        bundle.writestr("MANIFEST.txt", "\n".join(manifest_lines))
        for name, content, _description in files:
            bundle.writestr(name, content)
    return manifest_rows
