"""
Generate the validation documentation set for the current version.

Usage:  python tools/make_docs.py     (from the project root)

Writes two PDFs to docs/validation/:

1. v{VERSION}-technical-validation.pdf
   The full methodology document: architecture, data sources, algorithms,
   integrity controls, and verification procedures, written so an outside
   expert can examine and independently validate the software for court.

2. v{VERSION}-overview.pdf
   The 30,000-foot companion: what the tool does, what it refuses to do,
   and how to install and run it.

Numbers (thresholds, caps, defaults) are pulled live from app.config so
the documents can never silently drift from the code they describe. The
technical document also embeds the SHA-256 of this version's complete
source listing, giving reviewers a fixed integrity anchor.
"""

import hashlib
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (PageBreak, Paragraph, SimpleDocTemplate,
                                Spacer, Table, TableStyle)

import make_listing
from app import config

OUTPUT_DIR = PROJECT_ROOT / "docs" / "validation"
PAGE_MARGIN = 0.8 * inch


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": base["Title"],
        "h1": base["Heading1"],
        "h2": base["Heading2"],
        "body": ParagraphStyle("vbody", parent=base["BodyText"],
                               spaceAfter=6, leading=13),
        "bullet": ParagraphStyle("vbullet", parent=base["BodyText"],
                                 leftIndent=16, spaceAfter=3, leading=13),
        "small": ParagraphStyle("vsmall", parent=base["BodyText"],
                                fontSize=8, leading=10),
        "mono": ParagraphStyle("vmono", parent=base["BodyText"],
                               fontName="Courier", fontSize=8, leading=10),
    }


def _kv_table(rows, styles):
    data = [[Paragraph(f"<b>{k}</b>", styles["small"]),
             Paragraph(str(v), styles["small"])] for k, v in rows]
    table = Table(data, colWidths=[1.9 * inch, 5.0 * inch])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#b7c1cc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1),
         [colors.white, colors.HexColor("#f5f8fa")]),
    ]))
    return table


def _add(story, styles, heading, paragraphs, level="h1"):
    """Append a heading and its body. Strings starting '• ' are bullets."""
    if heading:
        story.append(Paragraph(heading, styles[level]))
    for text in paragraphs:
        style = styles["bullet"] if text.startswith("• ") else styles["body"]
        story.append(Paragraph(text, style))


def _listing_hash() -> tuple:
    """(relative path, sha256) of the current version's source listing,
    regenerating it first so the hash matches the code as it stands."""
    make_listing.main()
    listing = (PROJECT_ROOT / "docs" / "listings" /
               f"v{config.APP_VERSION}-full-listing.txt")
    digest = hashlib.sha256(listing.read_bytes()).hexdigest()
    return (f"docs/listings/{listing.name}", digest)


# ===========================================================================
# Document 1: technical validation
# ===========================================================================

def build_validation(pdf_path: Path, generated: str, listing_rel: str,
                     listing_sha: str) -> None:
    styles = _styles()
    story = []
    doc = SimpleDocTemplate(
        str(pdf_path), pagesize=letter,
        leftMargin=PAGE_MARGIN, rightMargin=PAGE_MARGIN,
        topMargin=PAGE_MARGIN, bottomMargin=PAGE_MARGIN,
        title=f"{config.APP_NAME} v{config.APP_VERSION} - "
              f"Technical Validation Document")

    story.append(Paragraph(f"{config.APP_NAME}", styles["title"]))
    story.append(Paragraph("Technical Validation Document",
                           styles["h1"]))
    story.append(Spacer(1, 6))
    story.append(_kv_table([
        ("Software version", f"v{config.APP_VERSION} (file: VERSION)"),
        ("Document generated", generated),
        ("Generated by", "tools/make_docs.py (part of the audited source)"),
        ("Complete source listing", listing_rel),
        ("Listing SHA-256", listing_sha),
        ("Audience", "Independent technical experts, prosecutors, and "
                     "courts evaluating the reliability of this tool's "
                     "output"),
    ], styles))
    story.append(Spacer(1, 10))

    _add(story, styles, "1. Purpose and scope", [
        "This tool follows cryptocurrency from a victim's wallet across "
        "public blockchains until the funds reach a custodial service (an "
        "exchange or similar business) on which legal process can be "
        "served. Its deliverable is a set of exit points - addresses, "
        "transaction IDs, timestamps and amounts - packaged with draft "
        "records-request language and a complete chain-of-custody log.",
        "<b>What the tool does not do.</b> It does not identify natural "
        "persons; account-holder identity must come from the custodian's "
        "KYC records via subpoena or warrant. It does not 'demix' mixing "
        "services, guess at continuity across privacy tools, or produce "
        "risk scores. It uses only public data, and it never presents an "
        "inference as a fact: every attribution and heuristic carries a "
        "stated confidence level and basis.",
    ])

    _add(story, styles, "2. Design principles", [
        "• <b>Facts are separated from inferences.</b> On-chain "
        "transactions (IDs, amounts, timestamps) are reported as facts. "
        "Roles, attributions and classifications are inferences, each "
        "carrying a confidence level (HIGH / MEDIUM / LOW) and a written "
        "basis stating its source.",
        "• <b>Dead ends are reported honestly.</b> Mixers, smart "
        "contracts, privacy coins and unlabelled busy services stop the "
        "trace and are flagged as such. The tool never fabricates "
        "continuity through an obstacle.",
        "• <b>Every data acquisition is reproducible.</b> Each network "
        "pull is recorded with its exact request URL, UTC timestamp, HTTP "
        "status, and the SHA-256 hash of the raw response body, so any "
        "analyst can re-issue the request and compare hashes.",
        "• <b>Public data only.</b> All sources are publicly accessible; "
        "no proprietary attribution database is used or simulated.",
        "• <b>Local and offline-safe.</b> The application binds to "
        f"{config.SERVER_HOST} only; case data never leaves the machine.",
    ])

    _add(story, styles, "3. System architecture", [
        "The software is a single-machine Python application (FastAPI "
        "web server, SQLite storage, browser-based user interface). No "
        "component is exposed to the network; the server listens on "
        f"{config.SERVER_HOST}:{config.SERVER_PORT} (localhost) only.",
        "Modules, each inlined in full in the source listing:",
        "• <b>app/config.py</b> - every tunable constant (thresholds, "
        "caps, endpoints) in one auditable file; no logic.",
        "• <b>app/database.py</b> - SQLite schema and access: cases, "
        "traces, settings, labels, the immutable HTTP evidence cache, "
        "the chain-of-custody log, and IC3 worksheet drafts.",
        "• <b>app/providers/</b> - data acquisition clients (Bitcoin via "
        "the Esplora API in pool / keyed / self-hosted modes; Ethereum "
        "via Blockscout, Routescan, Etherscan V2 or Alchemy; Tron via "
        "TronGrid) built on a shared base class that enforces cache, "
        "throttle, retry, custody logging and per-provider counters for "
        "every request (GET and JSON-RPC POST).",
        "• <b>app/labels/</b> - attribution store: OFAC SDN parsing, "
        "GraphSense TagPack, ScamSniffer and eth-labels importers, the "
        "bundled seed list, the agency's own flags, and partner flag "
        "packs (export/import with integrity hash).",
        "• <b>app/intel/</b> - on-demand Chainabuse lookups (budgeted, "
        "cached), plain-language wallet summaries (no AI) and bulk "
        "address triage.",
        "• <b>app/tracing/</b> - input format detection, the forward/"
        "backward tracing engine and Bitcoin common-input clustering.",
        "• <b>app/prices.py</b> - USD context values (CoinGecko with "
        "keyless Kraken/Coinbase fallbacks).",
        "• <b>app/report/</b> - the court-ready trace report, freeze/"
        "preservation letters, affidavit and traceroute text, the "
        "evidence package, and the IC3 worksheet (PDF generation).",
        "• <b>app/scheduler.py</b> - wallet-watch checks and label "
        "auto-refresh; <b>app/secretstore.py</b> - DPAPI encryption of "
        "keys; <b>app/assistant.py</b> - the optional AI assistant with "
        "its audit log; <b>app/launcher.py</b> - the console-free tray "
        "launcher.",
        "• <b>app/ic3.py</b> - IC3 complaint worksheet data model and "
        "trace prefill.",
        "• <b>app/static/</b> - the browser interface (plain HTML/JS/CSS; "
        "the only third-party component is the bundled Cytoscape.js "
        "graph library, served locally).",
    ])

    _add(story, styles, "4. Data sources", [
        "• <b>Bitcoin:</b> the Esplora REST API. Default 'pool' mode "
        f"rotates {config.DEFAULT_BITCOIN_API_BASE}, "
        f"{config.FALLBACK_BITCOIN_API_BASE} and a community host, which "
        "serve the identical API; 'keyed' mode uses the Blockstream "
        "Explorer API with agency credentials; 'custom' mode uses a "
        "single agency-run node. The custody log records the exact host "
        "and URL of every pull; immutable records share one evidence-"
        "cache entry regardless of host.",
        "• <b>Ethereum and ERC-20 tokens:</b> keyless Blockscout "
        "(default) or Routescan; with a free key, Etherscan V2 "
        f"({config.DEFAULT_ETHERSCAN_API_BASE}) or Alchemy (JSON-RPC, "
        "including internal transactions); or an agency-run Blockscout. "
        "Keys are excluded from logged URLs and cache keys, and Alchemy "
        "calls are logged as key-free descriptors, so custody logs are "
        "shareable and re-runnable by another analyst using their own "
        "key.",
        "• <b>Tron and TRC-20 tokens:</b> the official TronGrid API "
        f"({config.DEFAULT_TRONGRID_API_BASE}); keyless at a low rate, "
        "a free key raises the limit (sent as a header, never logged).",
        "• <b>Sanctions attribution:</b> the official US Treasury OFAC "
        f"SDN list, downloaded live from {config.OFAC_SDN_XML_URL} and "
        "parsed for digital-currency addresses. Imported at HIGH "
        "confidence (official government source). Never cached - each "
        "refresh records which snapshot (by hash) was used.",
        "• <b>Exchange / mixer attribution:</b> GraphSense TagPacks "
        "(MIT community packs, hundreds of thousands of addresses, pack "
        "provenance and last-modified date on every label), Etherscan "
        "public name tags via the MIT eth-labels dataset (Ethereum), and "
        "a small bundled seed list. All imported at MEDIUM confidence "
        "and marked as community/explorer tags, not official records. "
        "Every report states that absence of an exchange label is not "
        "evidence of absence.",
        "• <b>Scam-report corroboration:</b> the ScamSniffer public "
        "drainer blacklist, Etherscan 'Take Action'/exploit tags, and "
        "on-demand Chainabuse (TRM Labs) lookups. These are third-party, "
        "unverified reports: raised as corroborating findings, never as "
        "stopping points or proof.",
        "• <b>Agency designations:</b> the agency's own wallet flags "
        "(presented everywhere as the agency's own) and partner "
        "agencies' flag packs (a separate source, always named as the "
        "originating agency's designation; integrity-hashed on import).",
        "• <b>USD prices (context only):</b> CoinGecko public API "
        f"({config.COINGECKO_API_BASE}) with keyless Kraken and Coinbase "
        "daily-candle fallbacks. Not evidence; see section 8.",
    ])

    _add(story, styles, "5. Acquisition integrity (chain of custody)", [
        "All network access flows through one code path "
        "(app/providers/base.py) that applies, in order:",
        "• <b>Evidence cache.</b> Confirmed on-chain data is immutable, "
        "so the first captured response for a given request is stored "
        "permanently in SQLite (raw bytes + SHA-256) and served from "
        "disk thereafter; existing entries are never overwritten. Data "
        "that can change (address activity, sanctions list, prices for "
        "the current day) is deliberately never cached.",
        "• <b>Throttling.</b> A per-source minimum request interval "
        "keeps the tool inside free-tier limits (e.g. "
        f"{config.MIN_REQUEST_INTERVAL_SECONDS['mempool.space']}s for "
        "mempool.space, "
        f"{config.MIN_REQUEST_INTERVAL_SECONDS['coingecko']}s for "
        "CoinGecko).",
        f"• <b>Retry.</b> Rate-limit and server errors back off "
        f"exponentially up to {config.MAX_RETRIES} attempts; a 404 is "
        "treated as a definitive answer and logged, not retried.",
        "• <b>Custody logging.</b> Every acquisition - live or from "
        "cache - is appended to the custody_log table with: source, the "
        "exact re-runnable request URL, HTTP status, SHA-256 of the raw "
        "body, whether it was served from the evidence cache, and a UTC "
        "timestamp. The full log exports as CSV and appears (up to a "
        "size cap) as an appendix in every trace report.",
    ])

    _add(story, styles, "6. Tracing algorithm", [
        "<b>6.1 Starting point.</b> A trace is anchored to the victim's "
        "wallet address, confirmed by the investigator. Optionally, one "
        "'focus transaction' hash restricts direction: only that "
        "payment's outputs leaving the victim wallet become the first "
        "hop (outputs returning to the victim wallet - change - are "
        "excluded). The engine verifies the wallet actually participates "
        "in the focus transaction: if the wallet is only a recipient, "
        "the trace falls back to the full wallet with a written warning; "
        "if the wallet is not in the transaction at all, the trace fails "
        "with an explicit error rather than tracing the wrong funds. For "
        "a multi-input Bitcoin transaction, outputs are attributed to "
        "the payment as a whole and the report says so. In a focus-"
        "transaction trace, hops are counted from the FIRST SUSPECT "
        "WALLET (the payment's recipient); the focus payment itself is "
        "the approach to hop 1.",
        "<b>6.1a Time-forward rule.</b> Money cannot flow backward in "
        "time: every address in the trace is examined only from the "
        "moment the traced funds arrived at it, and movements dated "
        "earlier are ignored (their count appears in a written warning). "
        "A suspect wallet's unrelated prior history therefore cannot "
        "enter the trace.",
        "<b>6.2 Expansion.</b> The engine walks breadth-first from the "
        "starting point, following outgoing movements hop by hop up to a "
        f"user-set depth (1-{config.MAX_DEPTH_LIMIT} hops; default "
        f"{config.DEFAULT_MAX_DEPTH}). The investigator may instead "
        "select EXTENDED mode (with or without a focus transaction): "
        "every branch is followed until it resolves into a classified "
        "outcome (section 6.6), bounded by "
        f"{config.EXTENDED_MAX_DEPTH} hops and the size caps in 6.5. "
        "Movements below the dust "
        f"thresholds (defaults {config.DEFAULT_DUST_THRESHOLD_BTC} BTC / "
        f"{config.DEFAULT_DUST_THRESHOLD_ETH} ETH / "
        f"{config.DEFAULT_DUST_THRESHOLD_TOKEN_USD} token units, "
        "user-adjustable) are not followed. Value accounting is "
        "taint-by-touch ('poison'): every qualifying outgoing movement "
        "is followed in full; per-unit apportionment (FIFO/haircut) is "
        "not applied, and every report states this.",
        "<b>6.2a Search patterns.</b> The investigator selects a "
        "branch-selection policy per trace, and the report names it: "
        f"RAPID follows, per address and per asset, the largest outgoing "
        f"movements covering {config.RAPID_VALUE_COVERAGE:.0%} of the "
        f"outgoing value (max {config.RAPID_MAX_BRANCHES} branches); "
        f"BALANCED follows movements carrying at least "
        f"{config.BALANCED_MIN_BRANCH_FRACTION:.0%} of the outgoing value "
        f"(max {config.BALANCED_MAX_BRANCHES} branches); THOROUGH follows "
        "every movement above the dust threshold. Selective search is "
        "never presented as complete search: every skipped branch is "
        "counted (with per-asset value totals) in a written notice, "
        "itemised in the JSON export, and the affected addresses are "
        "flagged. The intended workflow is Rapid/Balanced to locate the "
        "custodian quickly, then a Thorough re-trace for the complete "
        "court record.",
        "<b>6.3 Movement semantics.</b> Bitcoin: for each transaction "
        "where the traced address appears in an input, each output is a "
        "movement; outputs paying the traced address itself are treated "
        "as change and excluded; non-standard outputs (e.g. OP_RETURN) "
        "have no destination address and are skipped. Ethereum: native "
        "ETH transfers plus ERC-20 token transfers sent from the traced "
        "address, newest first; reverted transactions and zero-value "
        "contract calls are skipped; token amounts use the token's "
        "reported decimals, with USDT/USDC handled by vetted constants.",
        "<b>6.4 Classification.</b> Before an address is expanded it is "
        "classified, in this priority order, and stopping roles are not "
        "expanded further: (1) OFAC-sanctioned (official list, HIGH "
        "confidence); (2) labelled mixing service - flagged 'trail "
        "obscured', never guessed through; (3) labelled exchange - "
        "recorded as an EXIT POINT, the deliverable; (4) smart contract "
        "(Ethereum) - flagged, not followed; (5) high-activity heuristic "
        f"- an address with more than "
        f"{config.HIGH_ACTIVITY_TX_THRESHOLD:,} transactions is treated "
        "as a probable service and not expanded (explicitly labelled a "
        "LOW-confidence heuristic); otherwise (6) intermediary "
        "pass-through. Exit detection also runs the moment an edge "
        "lands on a labelled exchange, so exits at the depth limit are "
        "still captured.",
        "<b>6.5 Safety caps (all reported when hit).</b> Per address, "
        f"only the most recent {config.MAX_OUTGOING_TXS_PER_ADDRESS} "
        "outgoing transactions are followed; a trace is capped at "
        f"{config.MAX_TOTAL_ADDRESSES_PER_TRACE} addresses and "
        f"{config.MAX_TOTAL_EDGES_PER_TRACE} movements. When any cap or "
        "the depth limit stops exploration, the affected addresses are "
        "marked 'unexpanded / trail edge' in the map, the report and "
        "the warnings - the tool records where it stopped looking.",
    ])

    _add(story, styles, "6a. Outcome classification and findings", [
        "Reaching a labelled exchange is not the only useful ending, so "
        "every branch ending is classified into an investigative outcome "
        "and reported: NAMED EXCHANGE (serve process); FUNDS AT REST (an "
        "address that received traced funds and shows no onward movement "
        "as of the trace time - a freeze/seizure/monitoring candidate); "
        "PROBABLE EXCHANGE DEPOSIT (a heuristic, stated as such: an "
        "address that forwarded at least "
        f"{config.SWEEP_MIN_FORWARD_RATIO:.0%} of its traced inflow "
        f"within {config.SWEEP_MAX_GAP_HOURS} hours into a high-activity "
        "wallet - the classic deposit-address fingerprint); UNIDENTIFIED "
        "BUSY SERVICE (probably nameable via public block-explorer tags); "
        "CONSOLIDATION POINT (two or more traced branches merging - a "
        "collection wallet, useful for linking victims); OFAC-SANCTIONED "
        "or MIXER contact; contact with a wallet FLAGGED BY THIS AGENCY "
        "(cross-case link) or FLAGGED BY A PARTNER AGENCY (imported "
        "pack, named as that agency's designation); contact with a "
        "PUBLICLY REPORTED SCAM ADDRESS (corroboration, not proof); a "
        "Bitcoin ADDRESS CLUSTER (several traced addresses presumed one "
        "wallet under the common-input-ownership heuristic, CoinJoin-"
        "like transactions excluded, evidencing transactions listed, "
        "MEDIUM or LOW confidence); and UNRESOLVED TRAIL EDGES (re-trace "
        "candidates). Each finding carries the underlying facts, its "
        "heuristic basis where applicable, and a recommended next step.",
        "A DISPOSITION OF FUNDS table accounts for the traced value "
        "arriving at every terminal bucket, including an explicit 'not "
        "examined' bucket totalling what the dust threshold and search "
        "pattern skipped. Because accounting is taint-by-touch, terminal "
        "amounts can include co-mingled third-party funds, and the "
        "report says so.",
    ])

    _add(story, styles, "7. Attribution and confidence model", [
        "Attribution labels live in one table with their source and "
        "confidence, and reports print both. The tiers are:",
        "• <b>HIGH</b> - official source (US Treasury OFAC SDN list) or "
        "multiple corroborating sources.",
        "• <b>MEDIUM</b> - a single reputable public/community source "
        "(e.g. a block-explorer entity tag); unverified.",
        "• <b>LOW</b> - a heuristic inference produced by this tool's "
        "own analysis (e.g. the high-activity flag).",
        "A role assigned during tracing (victim, intermediary, exchange, "
        "sanctioned, mixer, contract, high-activity, unexpanded) is an "
        "analytical inference; each node's written basis states exactly "
        "why it was assigned, and the report's address table reproduces "
        "these bases verbatim.",
        "<b>Compliance designations.</b> Identified exchanges may "
        "additionally carry a COMPLIANT / NON-COMPLIANT designation from "
        "a locally stored, agency-editable list (data/labels/"
        "exchange_compliance.json), used to guide legal-process strategy "
        "(cooperative custodian vs. MLAT or alternatives). Every surface "
        "that shows the designation states its provenance: it is the "
        "investigating agency's own designation made with reference to "
        "FATF (Financial Action Task Force) guidance - NOT an official "
        "FATF publication, as FATF evaluates jurisdictions rather than "
        "individual businesses.",
    ])

    _add(story, styles, "8. USD valuation (context, not evidence)", [
        "Movements in BTC and ETH are annotated with an approximate USD "
        "value computed from CoinGecko's daily price for the "
        "transaction's UTC date; USDT and USDC are valued at $1.00 by "
        "the peg; all other tokens are left unvalued rather than "
        "guessed. Intraday movement is not captured. Every surface that "
        "shows a USD figure labels it an estimate, and the report's "
        "methodology section repeats the limitation. Price requests go "
        "through the same custody-logged pipeline as blockchain data; "
        "past dates are immutable and cached, the current day is not. A "
        "price-source outage degrades the trace to crypto-only amounts "
        "with a warning - it can never change or fail a trace. The live "
        "ticker in the interface is display-only and stored nowhere.",
    ])

    _add(story, styles, "9. Outputs", [
        "• <b>Trace report (PDF)</b> - case summary; ranked exit points "
        "with funding transactions; DRAFT records-request language per "
        "custodian (marked for counsel review); address table with "
        "role bases; complete transaction table; methodology and "
        "limitations; chain-of-custody appendix.",
        "• <b>Chain-of-custody log (CSV)</b> - every acquisition for "
        "the trace, complete and machine-readable.",
        "• <b>Raw trace result (JSON)</b> - the full graph, exits and "
        "warnings for interoperability and archival.",
        "• <b>Fund-flow traceroute</b> - for every exit, a hop-by-hop "
        "path from the victim wallet to the exchange deposit address "
        "(addresses, amounts, USD estimates, transaction IDs, UTC "
        "times), printed in the report and exportable as plain text "
        "for quotation in a search warrant or affidavit.",
        "• <b>IC3 complaint worksheet (PDF)</b> - mirrors the section "
        "order and field labels of the official FBI complaint form at "
        "complaint.ic3.gov, prefilled from trace data where possible. "
        "IC3 offers no electronic submission; the worksheet is "
        "transcribed by a person, and the tool says so.",
        "• <b>Freeze / preservation request letters (PDF, DRAFT-"
        "watermarked)</b> - per receiving address, with the funding "
        "transactions as Attachment A, addressed to the attributed "
        "custodian or, for traced USDT/USDC at an unattributed wallet, "
        "to the token issuer; counsel review required before service.",
        "• <b>Affidavit methodology draft (text)</b> - numbered "
        "paragraphs describing sources, method, scope, attribution "
        "framework, records integrity and (when applied) clustering.",
        "• <b>Evidence package (ZIP)</b> - all of the above for one trace "
        "plus a manifest listing the SHA-256 of every packaged file.",
        "• <b>Map image (PNG)</b>, <b>bulk-triage table (CSV)</b>, "
        "<b>case export (JSON)</b> and <b>flag pack (JSON, hashed)</b>.",
    ])

    _add(story, styles, "10. Visualization integrity", [
        "The money-flow map offers readability aids: runs of one-in/"
        "one-out pass-through addresses collapse into a single dashed "
        "edge, multiple deposit addresses of one exchange group into an "
        "entity node, and sprays of small dead-end branches fold into a "
        "counted stub. These are display operations only. The underlying "
        "result - every address, movement, amount and hash - is "
        "unaffected: collapsed elements list their full contents when "
        "clicked, an 'Expand all' control shows every address "
        "individually, and the PDF, CSV and JSON exports always contain "
        "the complete data regardless of the display state.",
    ])

    _add(story, styles, "11. Known limitations", [
        "Each release ships a changelog (CHANGELOG.md) whose 'known "
        "limitations' sections are part of this validation record. "
        "Material limitations as of this version:",
        "• Only the most recent "
        f"{config.MAX_OUTGOING_TXS_PER_ADDRESS} outgoing transactions "
        "per address are examined; heavy later activity can conceal an "
        "older spend (a date-window filter is roadmapped).",
        "• Bitcoin clustering uses only the common-input-ownership "
        "heuristic over the transactions the trace parsed; change "
        "outputs to fresh addresses are otherwise followed like any "
        "other movement, and clusters are inferences with known failure "
        "modes (CoinJoin, custodial batching).",
        "• Funds entering smart contracts (swaps, bridges, mixers) are "
        "flagged and not traversed; no continuity is invented.",
        "• Exchange attribution comes from public community/explorer "
        "packs; per-customer deposit addresses are unlisted, so absence "
        "of an exit finding is not evidence of absence.",
        "• USD figures are daily-price approximations (section 8).",
        "• API keys are encrypted at rest with Windows DPAPI (user-"
        "scoped); disk encryption on the evidence machine is still "
        "recommended for the case database itself.",
        "• Monero and Litecoin inputs are recognised and explained but "
        "not traceable in this version (Monero is not traceable "
        "on-chain by design). Tron focus transactions are not supported.",
        "• Third-party scam reports and partner flags are unverified "
        "corroboration; the tool labels them so and never treats them "
        "as stopping points.",
    ])

    _add(story, styles, "12. Verification procedures for reviewers", [
        "<b>12.1 Identify the software.</b> The version is in the "
        "VERSION file and on every report. The complete source of this "
        f"version is inlined in a single file, {listing_rel}, whose "
        "SHA-256 appears on page 1 of this document. Comparing that "
        "hash validates that the code under review is the code that "
        "produced the output.",
        "<b>12.2 Reproduce any data pull.</b> Take any row of a trace's "
        "custody log, re-issue the recorded URL (for Etherscan rows, "
        "append your own free API key), hash the response body with "
        "SHA-256 and compare. Confirmed historical records (a "
        "transaction by ID) are immutable and must match exactly; "
        "address-level endpoints append new activity over time, which "
        "is why the log records the acquisition timestamp.",
        "<b>12.3 Reproduce a trace.</b> Given the report's victim "
        "wallet, focus transaction (if any), depth and dust parameters "
        "- all printed in the case summary - an independent "
        "installation of the same version will fetch the same "
        "underlying records and reach the same exit points, subject to "
        "label-list currency (the OFAC snapshot used is hash-logged).",
        "<b>12.4 Inspect the evidence store.</b> All data lives in "
        "data/investigator.db, a standard SQLite database openable "
        "with any SQLite tool. The http_cache table holds the raw "
        "response bytes exactly as received, alongside their hashes.",
        "<b>12.5 Examine the code.</b> The application is small by "
        "design (~a few thousand lines, no build step, dependencies "
        "pinned in requirements.txt: fastapi, uvicorn, httpx, "
        "reportlab). Every constant that affects tracing behaviour is "
        "in app/config.py. This document is itself generated by "
        "tools/make_docs.py from those constants, and both are part of "
        "the hashed source listing.",
    ])

    story.append(Spacer(1, 10))
    story.append(Paragraph(
        f"End of technical validation document for {config.APP_NAME} "
        f"v{config.APP_VERSION}, generated {generated}.", styles["small"]))
    doc.build(story)


# ===========================================================================
# Document 2: overview / quick start
# ===========================================================================

def build_overview(pdf_path: Path, generated: str) -> None:
    styles = _styles()
    story = []
    doc = SimpleDocTemplate(
        str(pdf_path), pagesize=letter,
        leftMargin=PAGE_MARGIN, rightMargin=PAGE_MARGIN,
        topMargin=PAGE_MARGIN, bottomMargin=PAGE_MARGIN,
        title=f"{config.APP_NAME} v{config.APP_VERSION} - Overview")

    story.append(Paragraph(config.APP_NAME, styles["title"]))
    story.append(Paragraph(
        f"Overview and Quick Start — v{config.APP_VERSION}, {generated}",
        styles["h2"]))

    _add(story, styles, "What it does", [
        "A cryptocurrency tracing and warrant-preparation tool for law "
        "enforcement. Starting from a victim's wallet, it follows stolen "
        "or scammed funds across the public blockchain until they reach "
        "a business - usually a crypto exchange - that can be served "
        "with a subpoena or warrant for the account holder's records. "
        "It then packages everything needed to draft that legal "
        "process: the deposit addresses, funding transactions, "
        "timestamps, amounts (with approximate USD values at the "
        "transaction dates), and draft records-request language.",
        "<b>It does not identify people.</b> It identifies where legal "
        "process can be served; the human behind an account comes from "
        "the exchange's KYC records via that process. It never guesses: "
        "everything that is an inference rather than an on-chain fact "
        "is labelled with a confidence level and its basis, and dead "
        "ends (mixers, privacy coins, smart contracts) are reported "
        "honestly.",
    ])

    _add(story, styles, "How it works, at 30,000 feet", [
        "1. The investigator creates a case and enters the victim's "
        "wallet address - and, if known, the transaction hash of the "
        "specific payment to the scammer, so only that payment is "
        "followed.",
        "2. The tool pulls public blockchain records and follows the "
        "money hop by hop (breadth-first, up to a chosen depth), "
        "recording every address and movement.",
        "3. Each address it reaches is checked against the official "
        "OFAC sanctions list, public exchange/mixer label packs, scam "
        "lists, the agency's own flags and partner agencies' flag "
        "packs, and classified: pass-through, exchange (an exit point), "
        "sanctioned, mixer, smart contract, or busy service. Bitcoin "
        "addresses spent together are grouped into clusters (a stated "
        "heuristic).",
        "4. Results appear as a left-to-right money-flow map (victim "
        "on the left, exits on the right) with plain-language "
        "explanations on every element, plus ranked exit-point cards.",
        "5. One click produces the evidence package: court-ready PDF "
        "report, chain-of-custody CSV, raw JSON, DRAFT affidavit "
        "methodology, per-exit traceroutes and DRAFT freeze letters "
        "with a SHA-256 manifest - plus an FBI IC3 complaint worksheet "
        "prefilled from the trace. Wallets can be watched for movement, "
        "flagged across cases, bulk-triaged, and checked against "
        "Chainabuse on demand.",
        "Every single network request the tool makes is logged with its "
        "exact URL, UTC time and a SHA-256 hash of the response, so an "
        "independent analyst can re-run and verify any piece of the "
        "work. A separate Technical Validation Document describes the "
        "methodology in full for expert review.",
    ])

    _add(story, styles, "Running the program", [
        "<b>Requirements:</b> Windows 10/11 (installed build) and a "
        "modern browser; from source, any OS with Python 3.10 or newer. "
        "Internet access for live tracing (previously fetched records "
        "are served from the local evidence cache).",
        "<b>Install (once):</b> run the setup program "
        "(CryptoInvestigator-Setup-v&lt;version&gt;.exe; no "
        "administrator rights needed) or unzip the portable build. From "
        "source: <font face='Courier'>python -m pip install -r "
        "requirements.txt</font>.",
        "<b>Start:</b> open Crypto Investigator from the Start menu or "
        "desktop shortcut (from source: <font face='Courier'>python "
        "run.py</font>). The browser opens at "
        f"<font face='Courier'>http://127.0.0.1:{config.SERVER_PORT}"
        "</font>; an icon in the notification area shows the program is "
        "running and offers Open and Quit. No console window appears. "
        "The app runs entirely on the local machine; nothing is exposed "
        "to the network and case data never leaves the computer.",
        "<b>Where data lives:</b> the installed build keeps its database, "
        "reports, logs and editable label files under "
        "%LOCALAPPDATA%\CryptoInvestigator\data (shown in Settings); "
        "a source checkout uses its own data/ folder. Either can be "
        "redirected (e.g. to an encrypted volume) with a data-location.txt "
        "file next to the program.",
        "<b>First-time setup (Settings button):</b> no accounts are "
        "required. Run the four label downloads once (OFAC sanctions "
        "list, exchange label packs, scam blacklist, Ethereum name "
        "tags); they refresh themselves afterwards. Fill in the agency letterhead if freeze "
        "requests will be generated. Optional free API keys only raise "
        "rate limits.",
        "<b>Workflow:</b> Step 1 create/pick a case → Step 2 paste the "
        "victim's wallet address → Step 3 (optional) paste the "
        "transaction hash of the payment to investigate → Step 4 choose "
        "how many hops to follow → press 'Follow the money' → review "
        "the exit points and map → download the report, custody log "
        "and IC3 worksheet.",
    ])

    _add(story, styles, "What comes out", [
        "• Court-ready fund-tracing report (PDF) with methodology, "
        "limitations and chain-of-custody appendices.",
        "• Chain-of-custody log (CSV) - every data pull, re-runnable.",
        "• Raw trace data (JSON) for archival or other tools.",
        "• FBI IC3 complaint worksheet (PDF) mirroring the official "
        "form at complaint.ic3.gov, prefilled with the traced "
        "payments.",
        "• DRAFT freeze / preservation request letters, affidavit "
        "methodology draft, per-exit traceroutes, map image, evidence "
        "ZIP with SHA-256 manifest, bulk-triage CSV, flag packs for "
        "partner agencies.",
    ])

    _add(story, styles, "Where to look next", [
        "• <b>Technical Validation Document</b> (docs/validation/) - "
        "full methodology, integrity controls, and step-by-step "
        "verification procedures for outside experts.",
        "• <b>CHANGELOG.md</b> - what each version added and its known "
        "limitations. <b>docs/listings/</b> - the complete source code "
        "of every version in a single hashed file.",
    ])

    doc.build(story)


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    listing_rel, listing_sha = _listing_hash()

    validation_path = (OUTPUT_DIR /
                       f"v{config.APP_VERSION}-technical-validation.pdf")
    build_validation(validation_path, generated, listing_rel, listing_sha)
    print(f"Wrote {validation_path}")

    overview_path = OUTPUT_DIR / f"v{config.APP_VERSION}-overview.pdf"
    build_overview(overview_path, generated)
    print(f"Wrote {overview_path}")


if __name__ == "__main__":
    main()
