"""
Plain-language wallet summary.

One short, honest paragraph set about an address, built ONLY from data the
tool already holds or can fetch with one or two throttled calls: label
attribution (with provenance), lifetime activity, this trace's view of the
address (what came in, what went out, to whom), the agency's own and
partners' designations, cached scam reports, and a suggested next step.

Every sentence maps to a fact in `facts`, so an analyst can check the
prose against the data. Nothing here is generated by a language model.
"""

from app import config, database
from app.intel import chainabuse
from app.labels import store as label_store


def _fmt(value, digits=6) -> str:
    return f"{value:,.{digits}f}".rstrip("0").rstrip(".")


def _activity(chain: str, address: str) -> dict:
    """Lifetime stats via the same snapshot the watch scheduler uses."""
    from app import scheduler
    snap = scheduler._snapshot(chain, address)
    per_unit = snap.get("per_unit") or 1
    return {
        "tx_count": snap.get("tx_count"),
        "balance": snap.get("balance_raw", 0) / per_unit,
        "unit": snap.get("unit", ""),
        "as_of": database.utc_now_iso(),
        "count_meaning": ("lifetime transactions" if chain == config.CHAIN_BITCOIN
                          else "outgoing transactions"),
    }


def _trace_view(result: dict, address: str) -> dict:
    nodes = {n["address"]: n for n in result.get("nodes", [])}
    node = nodes.get(address)
    if node is None:
        return {}
    inflow, outflow = {}, {}
    senders, receivers = set(), set()
    labelled_out = {}
    for edge in result.get("edges", []):
        asset = edge.get("asset", "")
        if edge.get("to_address") == address:
            inflow[asset] = inflow.get(asset, 0) + edge.get("value", 0)
            senders.add(edge.get("from_address"))
        if edge.get("from_address") == address:
            outflow[asset] = outflow.get(asset, 0) + edge.get("value", 0)
            receivers.add(edge.get("to_address"))
            target = nodes.get(edge.get("to_address"))
            if target and target.get("role") == config.ROLE_EXCHANGE:
                labelled_out[asset] = labelled_out.get(asset, 0) + \
                    edge.get("value", 0)
    labelled_share = None
    for asset, total in outflow.items():
        if total > 0 and asset in labelled_out:
            labelled_share = round(100 * labelled_out[asset] / total)
            break
    return {
        "role": node.get("role"), "depth": node.get("depth"),
        "basis": node.get("basis"), "flags": node.get("flags", []),
        "cluster": node.get("cluster"),
        "inflow": inflow, "outflow": outflow,
        "sender_count": len(senders), "receiver_count": len(receivers),
        "labelled_share_pct": labelled_share,
    }


def wallet_summary(chain: str, address: str, trace_result: dict = None,
                   fetch_activity: bool = True) -> dict:
    address = label_store.normalise_address(address, chain)
    chain_name = chain.capitalize()
    labels = label_store.lookup(address, chain)
    flag = database.flag_lookup(address, chain)
    watch = database.watch_lookup(address, chain)
    reports = chainabuse.cached(address, chain)
    facts = {"address": address, "chain": chain, "labels": labels,
             "flag": flag, "watched": bool(watch),
             "chainabuse": (None if reports is None else {
                 "report_count": reports.get("report_count", 0),
                 "categories": reports.get("categories", {}),
                 "fetched_utc": reports.get("fetched_utc")}),
             "activity": None, "activity_error": None, "trace": {}}
    paragraphs = []

    # 1. Attribution.
    attributions = [l for l in labels if l["category"] in
                    ("exchange", "mixer", "sanctioned", "other")]
    if attributions:
        parts = []
        for label in attributions[:3]:
            parts.append(f"{label['entity_name']} ({label['category']}, "
                         f"{label['confidence']} confidence, source "
                         f"{label['source']})")
        paragraphs.append(
            f"{chain_name} address {address} is attributed to "
            + "; ".join(parts) + ". Attribution comes from the named label "
            "source and carries that source's confidence; it is not an "
            "official record.")
    else:
        paragraphs.append(
            f"{chain_name} address {address} matches no label source loaded "
            f"in this tool. Absence of a label is not absence of a "
            f"service: exchange deposit addresses are unique per customer "
            f"and unlisted.")

    # 2. Activity.
    if fetch_activity:
        try:
            activity = _activity(chain, address)
            facts["activity"] = activity
            paragraphs.append(
                f"As of {activity['as_of'][:16].replace('T', ' ')} UTC it "
                f"shows {activity['tx_count']:,} {activity['count_meaning']} "
                f"and a balance of {_fmt(activity['balance'])} "
                f"{activity['unit']}"
                + (" (token balances are not included in this figure)."
                   if chain != config.CHAIN_BITCOIN else "."))
            if activity["tx_count"] and \
                    activity["tx_count"] > config.HIGH_ACTIVITY_TX_THRESHOLD:
                paragraphs.append(
                    "That volume is characteristic of a service (exchange, "
                    "payment processor, gambling site) rather than a "
                    "personal wallet - a heuristic, not a determination.")
        except Exception as exc:
            facts["activity_error"] = str(exc)
            paragraphs.append(
                f"Live activity could not be fetched right now ({exc}).")

    # 3. This trace.
    if trace_result:
        view = _trace_view(trace_result, address)
        facts["trace"] = view
        if view:
            role = (view.get("role") or "").replace("_", " ")
            article = "an" if role[:1] in "aeiou" else "a"
            inflow = ", ".join(f"{_fmt(v)} {a}" for a, v in
                               view["inflow"].items()) or "nothing"
            outflow = ", ".join(f"{_fmt(v)} {a}" for a, v in
                                view["outflow"].items()) or "nothing"
            sentence = (
                f"In this trace it is {article} {role} at hop "
                f"{view.get('depth')}: "
                f"it received {inflow} of traced funds from "
                f"{view['sender_count']} address(es) and sent {outflow} "
                f"onward to {view['receiver_count']} address(es).")
            if view.get("labelled_share_pct") is not None:
                sentence += (f" About {view['labelled_share_pct']}% of what "
                             f"it sent went directly to a labelled "
                             f"exchange.")
            if "no_onward_movements" in view.get("flags", []):
                sentence += (" The traced funds were still sitting here at "
                             "trace time (funds at rest).")
            if view.get("cluster"):
                sentence += (f" It belongs to address cluster "
                             f"{view['cluster']} (common-input heuristic; "
                             f"see the clusters section).")
            paragraphs.append(sentence)

    # 4. Designations and reports.
    designations = []
    if flag:
        designations.append(
            f"this agency flagged it on {(flag.get('created_utc') or '')[:10]}"
            + (f" ({flag['reason']})" if flag.get("reason") else ""))
    for label in labels:
        if label["category"] == config.LABEL_CATEGORY_SHARED_FLAG:
            designations.append(label["entity_name"].replace("Flagged by ",
                                                             "flagged by "))
        elif label["category"] == config.LABEL_CATEGORY_SCAM_REPORT and \
                label["source"] != config.LABEL_SOURCE_CHAINABUSE:
            designations.append(f"it appears on a public scam list "
                                f"({label['source']})")
    if reports is not None:
        count = reports.get("report_count", 0)
        if count:
            cats = ", ".join(sorted(reports.get("categories", {})))
            designations.append(
                f"Chainabuse holds {count} public report(s)"
                + (f" [{cats}]" if cats else "")
                + f" as of {(reports.get('fetched_utc') or '')[:10]}")
        else:
            designations.append(
                f"Chainabuse held no public reports as of "
                f"{(reports.get('fetched_utc') or '')[:10]}")
    if designations:
        paragraphs.append("Designations and reports: " +
                          "; ".join(designations) +
                          ". Reports and partner flags corroborate; they "
                          "do not prove.")
    if watch:
        paragraphs.append("This wallet is on the watch list; movement "
                          "raises an alert.")

    # 5. Suggested next step.
    if any(l["category"] == "exchange" for l in labels):
        step = ("Serve legal process on the attributed custodian for the "
                "account behind this address (see Legal contacts).")
    elif facts["trace"].get("flags") and \
            "no_onward_movements" in facts["trace"]["flags"]:
        step = ("Watch the wallet and prepare a freeze/preservation request "
                "now; if funds move, re-trace immediately.")
    elif reports is None:
        step = ("Run a Chainabuse lookup to see whether the public has "
                "reported this address, and check the block explorer for "
                "counterparties.")
    else:
        step = ("Re-trace from this address if the trail should continue, "
                "and consider flagging it so future cases hit it.")
    paragraphs.append("Suggested next step: " + step)

    return {"address": address, "chain": chain, "paragraphs": paragraphs,
            "facts": facts,
            "note": ("Generated from the tool's own data without any AI "
                     "model; every sentence corresponds to a fact in the "
                     "facts block.")}
